version: 2.1

workflows:
  version: 2
  build-deploy:
    jobs:
#      - build
      - deploy_ios_beta
orbs:
  ruby: circleci/ruby@2.0.0
  flutter: circleci/flutter@1.1.0
  macos: circleci/macos@2
jobs:
  build:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run:
          name: Configure key.properties
          command: |
            printf "
            keyAlias=%s
            keyPassword=%s
            storeFile=%s
            storePassword=%s
            " $RELEASE_KEY_ALIAS $RELEASE_KEY_PASSWORD "$(pwd)/android/keystore" $RELEASE_KEY_PASSWORD > android/key.properties
      - run: echo -n $BASE64_KEYSTORE | base64 -d > android/keystore
      - run: flutter doctor
      - run: flutter build apk
  deploy_android_beta:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run:
          name: Configure key.properties
          command: |
            printf "
            keyAlias=%s
            keyPassword=%s
            storeFile=%s
            storePassword=%s
            " $RELEASE_KEY_ALIAS $RELEASE_KEY_PASSWORD "$(pwd)/android/keystore" $RELEASE_STORE_PASSWORD > android/key.properties
      - run: echo -n $BASE64_KEYSTORE | base64 -d > android/keystore
      - run:
          name: Install fastlane in system
          command: gem install fastlane --no-document
          working_directory: ~/project/android
      - run:
          name: Upload android bundle in Google Play track beta
          command: fastlane beta
          working_directory: ~/project/android
  deploy_ios_beta:
    macos:
      xcode: 14.2.0
    steps:
      - checkout
      - run: echo -n $GOOGLE_PLAY_KEY > ios/gc_keys.json
      - macos/switch-ruby:
          version: "2.6.1"
      - run:
          name: Install fastlane in system
          command: gem install fastlane --no-document
          working_directory: ~/project/ios
      - flutter/install_sdk_and_pub:
          flutter_version: 3.7.2
      - run:
          name: Upload application to TestFlight
          command: fastlane beta
          working_directory: ~/project/ios
