version: 2.1

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy_android_beta
orbs:
  ruby: circleci/ruby@1.2.0

jobs:
  build:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run:
          name: Configure key.properties
          command: |
            printf "
            keyAlias=%s
            keyPassword=%s
            storeFile=%s
            storePassword=%s
            " $RELEASE_KEY_ALIAS $RELEASE_KEY_PASSWORD "$(pwd)/android/keystore" $RELEASE_STORE_PASSWORD > android/key.properties
      - run: echo $BASE64_KEYSTORE | base64 -d | tee keystore android/keystore
      - run: flutter channel
      - run: flutter doctor
      - run: flutter build apk
  deploy_android_beta:
    macos:
      xcode: 14.0.0
    working_directory: ~/merchant-app/android
    steps:
      - checkout
      - run: gem install fastlane
      - run: fastlane beta
