version: 2.1

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
orbs:
  ruby: circleci/ruby@1.2.0

jobs:
  build:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run:
          name: Configure key.properties
          command: |
            printf "
            keyAlias=%s
            keyPassword=%s
            storeFile=%s
            storePassword=%s
            " $RELEASE_KEY_ALIAS $RELEASE_KEY_PASSWORD "$(pwd)/android/keystore" $RELEASE_STORE_PASSWORD > android/key.properties
      - run: echo $BASE64_KEYSTORE | base64 -d | tee keystore android/keystore
      - run: flutter channel
      - run: flutter doctor
      - ruby/install-deps
      - run:
          name: fastlane
          command: SUPPLY_JSON_KEY_DATA=$GOOGLE_PLAY_KEY bundle exec fastlane run validate_play_store_json_key json_key_data:$GOOGLE_PLAY_KEY
      - run: flutter build apk
